@startuml
left to right direction
actor "Administrador" as admin
actor "Recepcionista" as rec
actor "Laboratorista" as lab

rectangle Acculab {
  usecase "Iniciar Sesión" as UC1
  usecase "Gestionar Usuarios" as UC2
  usecase "Gestionar Pacientes" as UC3
  usecase "Gestionar Pruebas y Perfiles" as UC4
  usecase "Crear y Gestionar Órdenes" as UC5
  usecase "Ingresar Resultados" as UC6
  usecase "Generar Reportes PDF" as UC7
  usecase "Ver Estadísticas/Finanzas" as UC8
}

admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC4
admin --> UC5
admin --> UC6
admin --> UC7
admin --> UC8

rec --> UC1
rec --> UC3
rec --> UC5
rec --> UC7
rec --> UC8

lab --> UC1
lab --> UC6
lab --> UC4
@enduml
